import { Link } from 'react-router-dom'

const journeys = [
  { title: 'Hajj packages', copy: 'Embark on the fifth pillar of Islam. Complete group packages with scholar guidance, premium hotels, and spiritual mentorship at every step.', image: '/hajj_banner.png', path: '/hajj-packages', tag: 'Seasonal departures' },
  { title: 'Umrah from India', copy: 'Experience the profound blessing of Umrah with well-planned packages from major Indian cities. Local guides, Indian cuisine, and seamless visa processing.', image: '/umrah_india.png', path: '/umrah-india', tag: 'Popular choice' },
  { title: 'Tailor-made Umrah', copy: 'Customize your sacred journey — choose your dates, preferred hotels, and family companions. A private itinerary built just for you.', image: '/tailor_made.png', path: '/tailor-made', tag: 'Made for you' },
]
const benefits = [['01', 'A clear spiritual path', 'From visa guidance to your return home, every detail is handled so you can focus on your worship.'], ['02', 'Premium Haram-view hotels', 'Stay close to Masjid al-Haram in Makkah and Masjid an-Nabawi in Madinah, minimizing travel time and maximizing spiritual focus.'], ['03', 'Devoted scholar support', 'Our team includes qualified Islamic scholars to guide you through all rituals, duas, and spiritual practices throughout your journey.']]
const included = [['Visa & Flight Arrangements', 'Complete Saudi Hajj/Umrah E-Visa processing and round-trip flights from India & UAE — no hidden hassles.'], ['5-Star Accommodation', 'Carefully curated hotels with Haram proximity, modern amenities, and halal dining — because comfort supports focus.'], ['Transportation & Logistics', 'VIP airport transfers, air-conditioned coaches, and inter-city Haramain rail or bus travel — all seamless and on schedule.'], ['Continuous Support', 'A responsive WhatsApp team and on-ground coordinators available 24/7 before, during, and after your pilgrimage.']]

function Arrow() { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h14M13 6l6 6-6 6" /></svg> }

export default function Home() {
  const whatsapp = 'https://wa.me/918110082222?text=Assalamu%20Alaikum%2C%20I%20would%20like%20help%20choosing%20a%20Hajj%20or%20Umrah%20package.'
  return <main className="home-refresh">
    <section className="refresh-hero"><img src="/hero-makkah-generated.png" alt="Masjid al-Haram in Makkah at dusk" /><div className="refresh-hero-shade" /><div className="refresh-hero-content"><p className="eyebrow-light">Crescent Haj Service · Trusted Since 2009 · 1000+ Happy Pilgrims</p><h1>Answer your heart's<br /><em>deepest calling.</em></h1><p className="hero-lede">Premium Hajj and Umrah packages combining spiritual guidance, luxury accommodations, and unwavering support. Make your pilgrimage a transformative journey, not a travel checklist.</p><div className="refresh-actions"><Link className="refresh-button refresh-button-gold" to="/umrah-packages">Start your journey <Arrow /></Link><a className="refresh-button refresh-button-outline" href={whatsapp} target="_blank" rel="noreferrer">Free consultation</a></div><div className="hero-note"><span className="live-dot" /> 24/7 WhatsApp support · India & UAE departures · Scholar-led groups</div></div><div className="hero-scroll">Scroll to explore <span /></div></section>

    <section className="journey-section section-pad"><div className="section-heading-row"><div><span className="eyebrow">Discover your pilgrimage</span><h2>Three paths to spiritual<br /><em>fulfillment.</em></h2><p style={{ marginTop: '12px', fontSize: '1rem', color: 'rgba(26,26,26,0.65)' }}>Whether you're answering the call of Hajj (the fifth pillar) or seeking the blessing of Umrah, we offer thoughtfully curated journeys tailored to your needs, timeline, and spiritual goals.</p></div><Link className="text-link" to="/umrah-packages">View all packages <Arrow /></Link></div><div className="journey-grid">{journeys.map((item, index) => <Link to={item.path} className={`journey-card ${index === 1 ? 'featured' : ''}`} key={item.title}><img src={item.image} alt={item.title} /><div className="journey-card-shade" /><div className="journey-card-copy"><span>{item.tag}</span><h3>{item.title}</h3><p>{item.copy}</p><b>Explore details <Arrow /></b></div></Link>)}</div></section>

    <section className="proof-section section-pad"><div className="proof-intro"><span className="eyebrow">Why choose Crescent</span><h2>Experience beyond<br /><em>a booking agency.</em></h2><p>More than logistics — we orchestrate transformation. Every detail of your pilgrimage is designed to remove worldly anxieties so you can fully immerse in worship, reflection, and spiritual connection with Allah.</p><Link className="text-link" to="/about">Learn our story <Arrow /></Link></div><div className="benefit-list">{benefits.map(item => <div className="benefit" key={item[0]}><strong>{item[0]}</strong><div><h3>{item[1]}</h3><p>{item[2]}</p></div></div>)}</div></section>

    <section className="included-section section-pad"><div className="included-visual"><img src="/madinah_mosque.png" alt="Masjid an-Nabawi in Madinah" /><div className="visual-caption"><span>Seamless support</span><strong>From booking<br />to blessed return.</strong></div></div><div className="included-copy"><span className="eyebrow">Complete pilgrimage care</span><h2>Everything arranged,<br /><em>nothing overlooked.</em></h2><div className="included-grid">{included.map((item, i) => <div key={item[0]}><span>0{i + 1}</span><h3>{item[0]}</h3><p>{item[1]}</p></div>)}</div><Link className="refresh-button refresh-button-dark" to="/contact">Begin your journey <Arrow /></Link></div></section>

    <section className="testimonial-section"><div className="quote-mark">"</div><blockquote>We felt completely cared for at every step. The scholar guidance transformed our Umrah from a trip into a spiritual awakening. Words cannot express our gratitude.</blockquote><p>— A Crescent pilgrim from Chennai</p><div className="rating">★★★★★ <span>1000+ pilgrims | 15+ years of trust</span></div><a className="testimonial-youtube-link" href="https://www.youtube.com/@CRESCENTHAJSERVICE/videos" target="_blank" rel="noreferrer">Watch real pilgrim testimonials on YouTube <Arrow /></a></section>
    <section className="final-cta"><div><span className="eyebrow-light">Your spiritual journey awaits</span><h2>Ready to answer<br /><em>your call?</em></h2><p style={{ marginTop: '16px', fontSize: '1.05rem', color: 'rgba(250,248,243,0.8)' }}>Connect with our pilgrimage advisors today. Free consultation, zero pressure. We're here to guide you home to the Haramain.</p></div><a className="refresh-button refresh-button-gold" href={whatsapp} target="_blank" rel="noreferrer">Start a conversation <Arrow /></a></section>
    <div className="mobile-action-bar"><Link to="/umrah-packages">Packages</Link><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href="tel:+918110082222">Call us</a></div>
  </main>
}
