import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { createPortal } from 'react-dom'

const journeys = [
  { title: 'Hajj packages', copy: 'Embark on the fifth pillar of Islam. Complete group packages with scholar guidance, premium hotels, and spiritual mentorship at every step.', image: '/hajj_banner.png', path: '/hajj-packages', tag: 'Seasonal departures' },
  { title: 'Umrah from India', copy: 'Experience the profound blessing of Umrah with well-planned packages from major Indian cities. Local guides, Indian cuisine, and seamless visa processing.', image: '/umrah_india.png', path: '/umrah-india', tag: 'Popular choice' },
  { title: 'Tailor-made Umrah', copy: 'Customize your sacred journey — choose your dates, preferred hotels, and family companions. A private itinerary built just for you.', image: '/tailor_made.png', path: '/tailor-made', tag: 'Made for you' },
]
const benefits = [['01', 'A clear spiritual path', 'From visa guidance to your return home, every detail is handled so you can focus on your worship.'], ['02', 'Premium Haram-view hotels', 'Stay close to Masjid al-Haram in Makkah and Masjid an-Nabawi in Madinah, minimizing travel time and maximizing spiritual focus.'], ['03', 'Devoted scholar support', 'Our team includes qualified Islamic scholars to guide you through all rituals, duas, and spiritual practices throughout your journey.']]
const included = [['Visa & Flight Arrangements', 'Complete Saudi Hajj/Umrah E-Visa processing and round-trip flights from India & UAE — no hidden hassles.'], ['5-Star Accommodation', 'Carefully curated hotels with Haram proximity, modern amenities, and halal dining — because comfort supports focus.'], ['Transportation & Logistics', 'VIP airport transfers, air-conditioned coaches, and inter-city Haramain rail or bus travel — all seamless and on schedule.'], ['Continuous Support', 'A responsive WhatsApp team and on-ground coordinators available 24/7 before, during, and after your pilgrimage.']]

function Arrow() { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h14M13 6l6 6-6 6" /></svg> }

const customerReviews = [
  { name: 'Sabiha Sultana', initials: 'SS', ago: 'Recent review', service: 'Umrah Service', text: 'Crescent Umrah & Hajj Services is one of the most trustworthy Umrah service providers. Their service was exceptional, and they took care of every arrangement from start to finish. We highly recommend them for a hassle-free and well-organized Umrah experience.', link: 'https://www.google.com/maps/contrib/111608337610501191994/reviews?hl=en-IN' },
  { name: 'Munaawara Banu', initials: 'MB', ago: 'Recent review', service: 'Peak Season Umrah', text: 'Crescent Haj Service organised our Umrah journey with care and professionalism in both Madinah and Makkah. Despite the peak-season crowds, everything was well coordinated. The team, guides, hotels, and logistics made the journey comfortable and meaningful.', link: 'https://www.google.com/maps/contrib/100035426218546749755/reviews?hl=en-IN' },
  { name: 'Ansari NM', initials: 'AN', ago: 'Recent review', service: 'Umrah & Hajj Service', text: 'Alhamdulillah, my family and I were very happy with all the services provided by the Crescent team. They stayed in constant contact, responded quickly, delivered food on time, and arranged excellent vehicles. We will always plan our Umrah and Hajj through Crescent.', link: 'https://www.google.com/maps/contrib/117744735499775852231/reviews?hl=en-IN' },
  { name: 'Hassan Mohamed', initials: 'HM', ago: 'Recent review', service: 'Umrah Service', text: 'I had an excellent experience with Crescent Haj Service. The Umrah service was outstanding, well organized, and professionally managed. Everything was smooth and hassle-free, and the team ensured all our requirements were fulfilled without delay.', link: 'https://www.google.com/maps/contrib/112527273426118218623/reviews?hl=en-IN' },
  { name: 'Farhath Aamir', initials: 'FA', ago: 'Recent review', service: 'Customised Umrah', text: 'I strongly recommend Crescent Umrah and Hajj Service for a pleasant pilgrimage. Their cabs, hotel-to-airport transfers, food, and moulavi guidance were outstanding. They also provide reliable customised plans on request.', link: 'https://www.google.com/maps/contrib/103967541975629886972/reviews?hl=en-IN' },
  { name: 'A Crescent pilgrim family', initials: 'CP', ago: 'Customer review', service: 'Pilgrimage Service', text: 'We felt completely cared for at every step. The scholar guidance transformed our Umrah from a trip into a spiritual awakening. Words cannot express our gratitude.', link: 'https://www.youtube.com/@CRESCENTHAJSERVICE/videos' },
]

function CustomerReviews() {
  return <section className="customer-review-showcase"><div className="customer-review-heading"><div><span className="eyebrow">Customer reviews</span><h2>Trusted by pilgrims<br /><em>across every journey.</em></h2></div><a className="review-google-link" href="https://www.google.com/maps/place/Crescent+Haj+Service/reviews" target="_blank" rel="noreferrer">View all Google reviews <Arrow /></a></div><div className="customer-review-window"><div className="customer-review-track">{[...customerReviews, ...customerReviews].map((review, index) => <article className="customer-review-card" key={`${review.name}-${index}`}><div className="customer-review-top"><div className="reviewer-identity"><span className="reviewer-avatar">{review.initials}</span><div><strong>{review.name}</strong><small>{review.ago}</small></div></div><a className="google-review-badge" href={review.link} target="_blank" rel="noreferrer"><span>G</span> REVIEW</a></div><div className="customer-stars">★★★★★</div><p className="customer-review-text">“{review.text}”</p><div className="customer-review-footer"><div><small>Service experience</small><strong>{review.service}</strong></div><span className="review-verified">✓</span></div></article>)}</div></div><div className="customer-review-dots" aria-hidden="true"><span /><span className="active" /><span /><span /></div></section>
}

function GeneralEnquiryPopup() {
  const [open, setOpen] = useState(true)

  useEffect(() => {
    document.body.style.overflow = open ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [open])

  if (!open) return null

  return createPortal(<div className="general-enquiry-modal" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setOpen(false) }}>
      <div className="general-enquiry-dialog" role="dialog" aria-modal="true" aria-labelledby="general-enquiry-title">
        <button className="general-enquiry-close" type="button" aria-label="Close general enquiry form" onClick={() => setOpen(false)}>×</button>
        <h2 id="general-enquiry-title">General enquiry</h2>
        <iframe title="General enquiry form" src="https://forms.zohopublic.in/GoimomiHolidays/form/WebsiteLead/formperma/EE3MFyvZhURPIlQK32BZ5cwdxx6DvziEjg70HxXJg5k?zf_rszfm=1" />
      </div>
    </div>, document.body)
}

export default function Home() {
  const whatsapp = 'https://wa.me/918110082222?text=Assalamu%20Alaikum%2C%20I%20would%20like%20help%20choosing%20a%20Hajj%20or%20Umrah%20package.'
  return <main className="home-refresh">
    <section className="refresh-hero"><img src="/hero-makkah-generated.png" alt="Masjid al-Haram in Makkah at dusk" /><div className="refresh-hero-shade" /><div className="refresh-hero-content"><p className="eyebrow-light">Crescent Haj Service · Trusted Since 2009 · 1000+ Happy Pilgrims</p><h1>Answer your heart's<br /><em>deepest calling.</em></h1><p className="hero-lede">Premium Hajj and Umrah packages combining spiritual guidance, luxury accommodations, and unwavering support. Make your pilgrimage a transformative journey, not a travel checklist.</p><div className="refresh-actions"><Link className="refresh-button refresh-button-gold" to="/umrah-packages">Start your journey <Arrow /></Link><a className="refresh-button refresh-button-outline" href={whatsapp} target="_blank" rel="noreferrer">Free consultation</a></div><div className="hero-note"><span className="live-dot" /> 24/7 WhatsApp support · India & UAE departures · Scholar-led groups</div></div><div className="hero-scroll">Scroll to explore <span /></div><GeneralEnquiryPopup /></section>

    <section className="journey-section section-pad"><div className="section-heading-row"><div><span className="eyebrow">Discover your pilgrimage</span><h2>Three paths to spiritual<br /><em>fulfillment.</em></h2><p style={{ marginTop: '12px', fontSize: '1rem', color: 'rgba(26,26,26,0.65)' }}>Whether you're answering the call of Hajj (the fifth pillar) or seeking the blessing of Umrah, we offer thoughtfully curated journeys tailored to your needs, timeline, and spiritual goals.</p></div><Link className="text-link" to="/umrah-packages">View all packages <Arrow /></Link></div><div className="journey-grid">{journeys.map((item, index) => <Link to={item.path} className={`journey-card ${index === 1 ? 'featured' : ''}`} key={item.title}><img src={item.image} alt={item.title} /><div className="journey-card-shade" /><div className="journey-card-copy"><span>{item.tag}</span><h3>{item.title}</h3><p>{item.copy}</p><b>Explore details <Arrow /></b></div></Link>)}</div></section>

    <section className="proof-section section-pad"><div className="proof-intro"><span className="eyebrow">Why choose Crescent</span><h2>Experience beyond<br /><em>a booking agency.</em></h2><p>More than logistics — we orchestrate transformation. Every detail of your pilgrimage is designed to remove worldly anxieties so you can fully immerse in worship, reflection, and spiritual connection with Allah.</p><Link className="text-link" to="/about">Learn our story <Arrow /></Link></div><div className="benefit-list">{benefits.map(item => <div className="benefit" key={item[0]}><strong>{item[0]}</strong><div><h3>{item[1]}</h3><p>{item[2]}</p></div></div>)}</div></section>

    <section className="included-section section-pad"><div className="included-visual"><img src="/madinah_mosque.png" alt="Masjid an-Nabawi in Madinah" /><div className="visual-caption"><span>Seamless support</span><strong>From booking<br />to blessed return.</strong></div></div><div className="included-copy"><span className="eyebrow">Complete pilgrimage care</span><h2>Everything arranged,<br /><em>nothing overlooked.</em></h2><div className="included-grid">{included.map((item, i) => <div key={item[0]}><span>0{i + 1}</span><h3>{item[0]}</h3><p>{item[1]}</p></div>)}</div><Link className="refresh-button refresh-button-dark" to="/contact">Begin your journey <Arrow /></Link></div></section>

    <section className="testimonial-section"><span className="eyebrow-light">Customer reviews</span><div className="testimonial-review-grid"><article className="testimonial-review-card"><div className="quote-mark">"</div><blockquote>Assalamualaikum w.r.w.b. I strongly recommend Crescent Umrah and Hajj Service for a pleasant pilgrimage. I liked the way they organized things for our Umrah trip, including cabs for Ziyarat, hotel-to-airport transfers, food, and a moulavi for guiding you while performing Umrah and Ziyarat. It is outstanding. Alhamdulillah, this is our second year with them and, InshaAllah, many more years to go. I have also recommended their services to extended family and friends. In short, a good, reliable, and trustworthy service. They also provide customised plans on request.</blockquote><p>— A Crescent pilgrim family</p><div className="rating">★★★★★ <span>Verified customer experience</span></div></article><article className="testimonial-review-card"><div className="quote-mark">“</div><blockquote>Crescent Umrah &amp; Hajj Services is one of the most trustworthy Umrah service providers. Alhamdulillah, this was our second time choosing them, and when we planned our Umrah again, we didn’t have to think twice before booking with them.<br /><br />Just as we expected, their service was exceptional. They took care of every personal arrangement, making our journey smooth and stress-free from start to finish. Their cab services were reliable, and their visa processing was incredibly efficient—they shared our visa and a detailed day-wise itinerary within just two days.<br /><br />We have already recommended Crescent Umrah &amp; Hajj Services to our extended family and friends, and we will continue to do so.<br /><br />I highly recommend them to anyone looking for a hassle-free and well-organized Umrah experience. May Allah reward the entire team for their excellent service. Ameen.</blockquote><p className="reviewer-name">— Sabiha Sultana</p><a className="review-source-link" href="https://www.google.com/maps/contrib/111608337610501191994/reviews?hl=en-IN" target="_blank" rel="noreferrer">View this review on Google Maps <Arrow /></a></article></div><a className="testimonial-youtube-link" href="https://www.youtube.com/@CRESCENTHAJSERVICE/videos" target="_blank" rel="noreferrer">Watch real pilgrim testimonials on YouTube <Arrow /></a></section>
    <section className="testimonial-section additional-review-section"><span className="eyebrow-light">Customer review</span><div className="testimonial-review-grid"><article className="testimonial-review-card"><div className="quote-mark">“</div><blockquote>Crescent Haj Service organised our Umrah journey with care and professionalism in both Madinah and Makkah. Our travel period was from 29 December 2025 to 10 January 2026, which coincided with peak season. Despite the heavy crowds in both cities, the arrangements were well coordinated and smoothly managed.<br /><br />During this journey, we were able to perform three Umrahs, all of which were well facilitated and organised, allowing us to focus fully on our ibadah without unnecessary stress.<br /><br />We would like to specially acknowledge Mr Ryaz, who coordinated with us throughout the planning stage, including flight bookings, hotel arrangements, and overall logistics. His responsiveness, clarity, and efficiency ensured a smooth and stress-free preparation for the journey.<br /><br />Ziyarah was arranged in both Madinah and Makkah, and in each city the Hajrath who accompanied us was highly knowledgeable. The explanations provided were clear and insightful, adding depth and meaning to the spiritual experience.<br /><br />We would also like to commend Mr Mubarak, the proprietor of Crescent Haj Service, who travelled with us throughout the journey. Despite his position, he remained consistently polite, humble, and approachable. He took personal interest in each and every traveller, maintaining a genuine connection with everyone in the group. His gentle temperament, patience, and calm presence made the journey comfortable and reassuring for all of us.<br /><br />Our stay in Makkah was at DoubleTree by Hilton, which was very comfortable. The hotel’s close proximity to the Haram, within a five minute walk, along with the 24 hour buggy service, was especially convenient.<br /><br />One area for improvement would be room allocation in Madinah, as the rooms were somewhat compact. However, this is a common limitation with many mid-range hotels in Madinah, particularly during peak periods.<br /><br />Overall, Crescent Haj Service delivered a well organised and meaningful Umrah experience. We appreciate the dedication of the team and would confidently recommend Crescent Haj Service to others planning their Umrah journey.</blockquote><p className="reviewer-name">— Munaawara Banu</p><a className="review-source-link" href="https://www.google.com/maps/contrib/100035426218546749755/reviews?hl=en-IN" target="_blank" rel="noreferrer">View this review on Google Maps <Arrow /></a></article></div></section>
    <section className="testimonial-section additional-review-section"><span className="eyebrow-light">Customer review</span><div className="testimonial-review-grid"><article className="testimonial-review-card"><div className="quote-mark">“</div><blockquote>Alhamdulillah. In the name of Allah, my family and I are very, very happy with all the services provided by the Crescent team. Right from our departure to Makkah and our return, they stayed in constant contact with me to make sure everything was okay. Their response time was very quick whenever I needed clarification.<br /><br />Alhamdulillah, my mind was fully focused on Umrah. I am very thankful to the team, who took care of us like family. The package was five-star, the food was delivered on time, and the vehicle arrangements were excellent. The GMC ride was outstanding. I will recommend Crescent to all my family members for their Umrah and Hajj, and will always plan only through the Crescent team.</blockquote><p className="reviewer-name">— Ansari NM</p><a className="review-source-link" href="https://www.google.com/maps/contrib/117744735499775852231/reviews?hl=en-IN" target="_blank" rel="noreferrer">View this review on Google Maps <Arrow /></a></article></div></section>
    <section className="testimonial-section additional-review-section"><span className="eyebrow-light">Customer review</span><div className="testimonial-review-grid"><article className="testimonial-review-card"><div className="quote-mark">“</div><blockquote>I had an excellent experience with Crescent Haj Service. Their Umrah service was truly outstanding, very well organized, and professionally managed. The entire team was highly supportive and ensured that all our requirements were fulfilled perfectly without any delay. From start to finish, everything was smooth and hassle-free. I sincerely appreciate their dedication and commitment, and I strongly recommend Crescent Haj Service to anyone looking for a reliable and trustworthy Umrah service.<br /><br />Once again, thanks for your guidance, Haji Mubarak brother, for the wonderful service.</blockquote><p className="reviewer-name">— Hassan Mohamed</p><a className="review-source-link" href="https://www.google.com/maps/contrib/112527273426118218623/reviews?hl=en-IN" target="_blank" rel="noreferrer">View this review on Google Maps <Arrow /></a></article></div></section>
    <section className="testimonial-section additional-review-section"><span className="eyebrow-light">Customer review</span><div className="testimonial-review-grid"><article className="testimonial-review-card"><div className="quote-mark">“</div><blockquote>Assalamualaikum w.r.w.b. I strongly recommend Crescent Umrah and Hajj Service for a pleasant pilgrimage. I liked the way they organized things for our Umrah trip, including cabs for Ziyarat, hotel-to-airport transfers, food, and a moulavi for guiding you while performing Umrah and Ziyarat. It is outstanding. Alhamdulillah, this is our second year with them and, InshaAllah, many more years to go. I have also recommended their services to extended family and friends. In short, a good, reliable, and trustworthy service. They also provide customised plans on request.</blockquote><p className="reviewer-name">— Farhath Aamir</p><a className="review-source-link" href="https://www.google.com/maps/contrib/103967541975629886972/reviews?hl=en-IN" target="_blank" rel="noreferrer">View this review on Google Maps <Arrow /></a></article></div></section>
    <CustomerReviews />
    <section className="final-cta"><div><span className="eyebrow-light">Your spiritual journey awaits</span><h2>Ready to answer<br /><em>your call?</em></h2><p style={{ marginTop: '16px', fontSize: '1.05rem', color: 'rgba(250,248,243,0.8)' }}>Connect with our pilgrimage advisors today. Free consultation, zero pressure. We're here to guide you home to the Haramain.</p></div><a className="refresh-button refresh-button-gold" href={whatsapp} target="_blank" rel="noreferrer">Start a conversation <Arrow /></a></section>
    <div className="mobile-action-bar"><Link to="/umrah-packages">Packages</Link><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href="tel:+918110082222">Call us</a></div>
  </main>
}
